1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

2. Create a random tensor with shape (7, 7).

In [1]:
import torch

tensor = torch.rand(7,7)
tensor

tensor([[0.8124, 0.9182, 0.1185, 0.5884, 0.0866, 0.4909, 0.6199],
        [0.9366, 0.8793, 0.8511, 0.8559, 0.5872, 0.8217, 0.1165],
        [0.8355, 0.6105, 0.4409, 0.8094, 0.6513, 0.1502, 0.7971],
        [0.8837, 0.1871, 0.4902, 0.6197, 0.1982, 0.8889, 0.0337],
        [0.6763, 0.7552, 0.2093, 0.4316, 0.1312, 0.7129, 0.3435],
        [0.1294, 0.7313, 0.5447, 0.4478, 0.8091, 0.9428, 0.1508],
        [0.8518, 0.0476, 0.6320, 0.2393, 0.1528, 0.7371, 0.6849]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [2]:
import torch
tensorA = torch.rand(1,7)
tensorB = torch.rand(1,7)

torch.matmul(tensorA,tensorB.T)

tensor([[2.4246]])

4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [8]:
import torch
randomSeed = 42

torch.manual_seed(randomSeed)
tensor = torch.rand(1,7)

torch.manual_seed(randomSeed)
tensorA = torch.rand(1,7)
torch.manual_seed(randomSeed)
tensorB = torch.rand(1,7)

x = torch.matmul(tensorA, tensorB.T)

print(f"tensor : {tensor}")
print(f"tensorA : {tensorA}")
print(f"tensorB : {tensorB}")
print(tensorA == tensorB)
print(f"tensorA * tensorB : {x}")


tensor : tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]])
tensorA : tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]])
tensorB : tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]])
tensor([[True, True, True, True, True, True, True]])
tensorA * tensorB : tensor([[3.2618]])


5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [9]:
# set random seed on GPU
torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [12]:
import torch
torch.manual_seed(1234)

# check gpu
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'device : {device}')
# create tensor

tensorA = torch.rand(2,3).to(device)
tensorB = torch.rand(2,3).to(device)

print(f'tensor A : {tensorA}')
print(f"tensor B : {tensorB}")

device : cpu
tensor A : tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor B : tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


Prform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [13]:
import torch
tensorA = torch.rand(2,3).to(device)
tensorB = torch.rand(2,3).to(device)
x = torch.matmul(tensorA, tensorB.T)

print(f'tensor A : {tensorA}')
print(f"tensor B : {tensorB}")
print(f'x : {x}')

tensor A : tensor([[0.7749, 0.8208, 0.2793],
        [0.6817, 0.2837, 0.6567]])
tensor B : tensor([[0.2388, 0.7313, 0.6012],
        [0.3043, 0.2548, 0.6294]])
x : tensor([[0.9531, 0.6207],
        [0.7651, 0.6931]])


8. Find the maximum and minimum values of the output of 7.


In [17]:
print(torch.min(x))
print(torch.max(x))

tensor(0.6207)
tensor(0.9531)


9. Find the maximum and minimum index values of the output of 7.


In [18]:
print(x.argmin())
print(x.argmax())

tensor(1)
tensor(0)


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [28]:
import torch

# Set seed
torch.manual_seed(7)

tensor = torch.rand(1,1,1,10)
tensor2 = tensor.squeeze()
tensor3 = tensor.unsqueeze(dim = 0)

print(f'tensor : {tensor}')
print(f'tensor2 : {tensor2}')
print(f'tensor3 : {tensor3}')
print(f'tensor : {tensor.shape}')
print(f'tensor2 : {tensor2.shape}')
print(f'tensor3 : {tensor3.shape}')

tensor : tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor2 : tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
tensor3 : tensor([[[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]])
tensor : torch.Size([1, 1, 1, 10])
tensor2 : torch.Size([10])
tensor3 : torch.Size([1, 1, 1, 1, 10])
