In [ ]:
# 00 pytorch fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## introduction to tensors
### creating tensors



In [ ]:
# scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

10

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[7,8],
                      [10,8]])
matrix

tensor([[ 7,  8],
        [10,  8]])

In [ ]:
 matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[1]

tensor([10,  8])

In [ ]:
# Tensor
tensor = torch.tensor([[[1,2],
                        [3,4],
                        [5,6]]])
tensor

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 2])

In [ ]:
tensor[0,0]

tensor([1, 2])

### Random Tensor

In [ ]:
#  create a random tensor of shape (1,3,4)
# 1 -> banyak variasi data tensor
# 3 -> banyak baris data tensor
# 4 -> banyak kolom data tensor
random_tensor = torch.rand(1,3,4)
random_tensor


tensor([[[0.8287, 0.7015, 0.0221, 0.3056],
         [0.5201, 0.0397, 0.4514, 0.2483],
         [0.5002, 0.9764, 0.1364, 0.3120]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([1, 3, 4])

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor

tensor([[[0.0891, 0.4502, 0.3064],
         [0.0620, 0.9077, 0.7080],
         [0.3217, 0.0715, 0.2339],
         ...,
         [0.5714, 0.7160, 0.1898],
         [0.9963, 0.5257, 0.4822],
         [0.7696, 0.0617, 0.1153]],

        [[0.2524, 0.2166, 0.6433],
         [0.6780, 0.0659, 0.9497],
         [0.5749, 0.0071, 0.2936],
         ...,
         [0.9053, 0.2310, 0.1326],
         [0.4780, 0.9247, 0.2963],
         [0.2825, 0.6731, 0.1799]],

        [[0.2468, 0.1762, 0.6081],
         [0.4763, 0.2537, 0.7184],
         [0.9465, 0.6566, 0.8354],
         ...,
         [0.6765, 0.8833, 0.8615],
         [0.6238, 0.9520, 0.3200],
         [0.1124, 0.1716, 0.8606]],

        ...,

        [[0.2637, 0.6820, 0.6414],
         [0.1177, 0.7218, 0.2959],
         [0.6575, 0.8869, 0.8649],
         ...,
         [0.4809, 0.7611, 0.5687],
         [0.7137, 0.0975, 0.6487],
         [0.7921, 0.8722, 0.8454]],

        [[0.2077, 0.8449, 0.6088],
         [0.8726, 0.2723, 0.6615],
         [0.

### Zero and Ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros.dtype

torch.float32

### Creatin a range  of tensors and tensors like

In [ ]:
# use tensor range
one_to_tweleve = torch.arange(1,20,3)
one_to_tweleve

tensor([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
# creating tensor like
one_to_ten = torch.arange(1,11)
print(one_to_ten)
ten_zeros = torch.zeros_like(input= one_to_ten)
print(ten_zeros)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor data type

**Note:** Tensor datatype is one of the 3 big error youll run into with pytorch and deep learning
1. tensors not right datatype
2. tensors not right shape
3. tensors not on the right device


In [ ]:
# float32 tensor

float32_tensor = torch.tensor([3.0,5.0,4.0],dtype=None, # what datatype is the tensor
                              device = "cuda", # what device is your tensor on
                              requires_grad = False) # wheter or no to track gradients with this tensors operations
float32_tensor

tensor([3., 5., 4.], device='cuda:0')

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
float16_tensors = float32_tensor.type(torch.float16)
float16_tensors

tensor([3., 5., 4.], device='cuda:0', dtype=torch.float16)

In [ ]:
temp = float16_tensors * float32_tensor
temp

tensor([ 9., 25., 16.], device='cuda:0')

In [ ]:
temp.dtype

torch.float32

In [ ]:
int32_tensor = torch.tensor([3,4,6], dtype= torch.long,
                            device = 'cuda')
int32_tensor

tensor([3, 4, 6], device='cuda:0')

In [ ]:
float32_tensor * int32_tensor

tensor([ 9., 20., 24.], device='cuda:0')

### getting information from tensors

1. tensors not right datatype - to do get datatype from a tensor, can use 'tensor.dtype'
2. tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. tensors not on the right device - to get device form a tensor, can use 'tensor.device'

In [ ]:
# create a tensor

someTensor = torch.rand(3,4)
someTensor

tensor([[0.1436, 0.5828, 0.4269, 0.3629],
        [0.6778, 0.1203, 0.2207, 0.6426],
        [0.2766, 0.5187, 0.5204, 0.6771]])

In [ ]:
# details about tensor
print(someTensor)
print(f"Datatype of tensor : {someTensor.dtype}")
print(f"Shape of tensor : {someTensor.shape}")
print(f"Device of tensor : {someTensor.device}")

tensor([[0.1436, 0.5828, 0.4269, 0.3629],
        [0.6778, 0.1203, 0.2207, 0.6426],
        [0.2766, 0.5187, 0.5204, 0.6771]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu


### Manipulating Tensor

Tensor operations include :
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [ ]:
# creating a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
# subtract
tensor - 10

tensor([ 0, 10, 20])

In [ ]:
# Try out pytorch in-built function
torch.mul(tensor,10)

tensor([100, 200, 300])

In [ ]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix multiplication

two main ways of performing multiplication in neural networks and deep learning

1. element-wise multiplication
2. matrix multiplication

there are two main rules that performing matrix multiplication needs to satisfy

1. the inner dimension must match:
* (3,2) @ (3,2) wont work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work

2. the result matrix has the shape of the outer dimension
* (3,2) @ (2,3) -> (3,3)
* (2,3) @ (3,2) -> (2,2)

In [ ]:
# element wise multlipication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30]) = tensor([100, 400, 900])


In [ ]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(1400)

In [ ]:
# # Matrix multiplication by hand
10 * 10 + 20 * 20 + 30 * 30

1400

In [ ]:
%%time

value  = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 3.74 ms, sys: 0 ns, total: 3.74 ms
Wall time: 3.48 ms


In [ ]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 29 µs, sys: 6 µs, total: 35 µs
Wall time: 37.9 µs


tensor(1400)

### one of the most common error in deep  learning: shape errors

In [ ]:
# shape for matrix multiplication

tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensorB = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])

torch.matmul(tensorA * tensorB)

TypeError: matmul() missing 1 required positional arguments: "other"

In [ ]:
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A transpose switches the axes or dimensions of a given tensor.

In [ ]:
tensorB.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [ ]:
tensorB

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
#  the matrix multiplication operation works when tensorB is transposed
print(f"Original shapes: tensorA = {tensorA.shape}, tensorB = {tensorB.shape}")
print(f"New shapes: tensorA = {tensorA.shape} (same shape as above), tensorB.T = {tensorB.T.shape}")
print(f"Multiplying: {tensorA.shape} @ {tensorB.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensorA, tensorB.T)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.matmul(tensorA, tensorB.T)

Original shapes: tensorA = torch.Size([3, 2]), tensorB = torch.Size([3, 2])
New shapes: tensorA = torch.Size([3, 2]) (same shape as above), tensorB.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
#  create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the position in tensor that has the minimum value with argmin() -> return index postion with minimum value
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
# find the position in tensor that has the minimum value with argmin() -> return index postion with minimum value
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to ad defined shape
* View - Return a view of an input tensor of certain shape but keep the same memorya s teh original tensor
* stacking - combine multiple tensors on top of each other (vstack) ir side by side (hstack)
* squeeze - remove `1` dimension from a tensor
* unsqueeze - add a `1` dimension to a target tensor
* permute - return a view of the input with dimensions permuted (swapped) in certain way

In [14]:
# creating a tensor
import torch

x = torch.arange(1., 10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [15]:
# add an extra dimension
xReshaped = x.reshape(1,9)
xReshaped, xReshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [16]:
# change the view

z = x .view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [17]:
# chaning z change x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [18]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [19]:
# torch.squeeze() - removes all single dimension from a target tensor

print(f'previous tensor : {xReshaped}')
print(f"Previous Shape : {xReshaped.shape}")

# remove extra dimension from xReshaped
xSqueezed = xReshaped.squeeze()
print(f"\nNew tensor : {xSqueezed}")
print(f"New Shape : {xSqueezed.shape}")

previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape : torch.Size([1, 9])

New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape : torch.Size([9])


In [20]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension

print(f"Previous tensor : {xSqueezed}")
print(f"Previous Shape : {xSqueezed.shape}")

# add an extra dimension with unsqueeze
xUnsqueezed = xSqueezed.unsqueeze(dim = 0)
print(f"\nNew tensor : {xUnsqueezed}")
print(f"New Shape : {xUnsqueezed.shape}")

Previous tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape : torch.Size([9])

New tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape : torch.Size([1, 9])


In [21]:
# torch.permute() - rearrange the dimension of a target tensor in a specific order
xOriginal = torch.rand(size = (224,224,3)) # height, widht, color channels

# permute the original tensor to rearrange the axis or dim order
xPermuted = xOriginal.permute(2,0,1) # shift axis 0 -> 1, 1 -> 2, 2 -> 0

print(f'Previous shape : {xOriginal.shape}')
print(f'New shape : {xPermuted.shape}')

Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [22]:
xOriginal

tensor([[[0.4033, 0.5835, 0.8182],
         [0.7966, 0.3219, 0.7915],
         [0.1263, 0.6246, 0.0403],
         ...,
         [0.1768, 0.4063, 0.2273],
         [0.3169, 0.8906, 0.4214],
         [0.9920, 0.9544, 0.5738]],

        [[0.0014, 0.6962, 0.4063],
         [0.7791, 0.2820, 0.1198],
         [0.4089, 0.0506, 0.7917],
         ...,
         [0.3348, 0.2369, 0.9870],
         [0.2031, 0.2079, 0.0723],
         [0.9545, 0.9688, 0.0191]],

        [[0.1166, 0.5892, 0.3525],
         [0.7939, 0.4719, 0.1933],
         [0.3493, 0.9101, 0.7196],
         ...,
         [0.4972, 0.7952, 0.5095],
         [0.4404, 0.9173, 0.9229],
         [0.0306, 0.1234, 0.1699]],

        ...,

        [[0.8944, 0.4099, 0.2482],
         [0.9486, 0.0224, 0.1941],
         [0.7264, 0.2489, 0.0248],
         ...,
         [0.1163, 0.5125, 0.1194],
         [0.6923, 0.1461, 0.7484],
         [0.6248, 0.1810, 0.0595]],

        [[0.5807, 0.9776, 0.3453],
         [0.4521, 0.7522, 0.1798],
         [0.

In [23]:
xOriginal[0,0,0]

tensor(0.4033)

In [24]:
xPermuted

tensor([[[0.4033, 0.7966, 0.1263,  ..., 0.1768, 0.3169, 0.9920],
         [0.0014, 0.7791, 0.4089,  ..., 0.3348, 0.2031, 0.9545],
         [0.1166, 0.7939, 0.3493,  ..., 0.4972, 0.4404, 0.0306],
         ...,
         [0.8944, 0.9486, 0.7264,  ..., 0.1163, 0.6923, 0.6248],
         [0.5807, 0.4521, 0.4595,  ..., 0.4570, 0.4125, 0.6822],
         [0.2949, 0.1872, 0.3697,  ..., 0.2883, 0.5964, 0.3552]],

        [[0.5835, 0.3219, 0.6246,  ..., 0.4063, 0.8906, 0.9544],
         [0.6962, 0.2820, 0.0506,  ..., 0.2369, 0.2079, 0.9688],
         [0.5892, 0.4719, 0.9101,  ..., 0.7952, 0.9173, 0.1234],
         ...,
         [0.4099, 0.0224, 0.2489,  ..., 0.5125, 0.1461, 0.1810],
         [0.9776, 0.7522, 0.0758,  ..., 0.8490, 0.3056, 0.0388],
         [0.7314, 0.7303, 0.7535,  ..., 0.2868, 0.4237, 0.7039]],

        [[0.8182, 0.7915, 0.0403,  ..., 0.2273, 0.4214, 0.5738],
         [0.4063, 0.1198, 0.7917,  ..., 0.9870, 0.0723, 0.0191],
         [0.3525, 0.1933, 0.7196,  ..., 0.5095, 0.9229, 0.

In [25]:
xOriginal[0,0,0] = 9999
xOriginal[0,0,0], xPermuted[0,0,0]

(tensor(9999.), tensor(9999.))

## Indexin (selecting data from tensor)

indexing with pytorch is similar to indexing with numpy

In [28]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [29]:
# lets index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
# lets index on the middle bracket (dim = 1)

x[0][1]

tensor([4, 5, 6])

In [35]:
# lets index on the most inner bracket

x[0][2][2]

tensor(9)

In [36]:
#  you can also use : to select all of a target dimension

x[0,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [41]:
# get all values of 0 and 1 dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [42]:
# get all values of the 0 dimension but only take the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [43]:
# get index 0 of 0 and 1 dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [45]:
# index x to return 9
print(x[0,2,2])

# index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


## pytorch tensor and numpy

numpy is a popular scientific python numerical computing libraryy

and because of this , pytorch has functionalitu to interact with it

* data in numpt, want in pytorch tensor -> `torch.from_numpy(ndarray)`
* pytorch -> numpy -> `torch.Tensor.numpy()`

In [53]:
# numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # WARNING : when converting from numpy -> pytorch, pytorch reflect numpy default datatype
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [50]:
array.dtype,tensor.dtype

(dtype('float64'), torch.float64)

In [52]:
torch.arange(1.0,8.0).dtype

torch.float32

In [54]:
# change the value of array , what will this do to tenosr
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [55]:
# tensor to numpy
tensor = torch.ones(8)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [56]:
numpy_tensor.dtype

dtype('float32')

In [57]:
# change the tensor, what happen to numpy

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

in short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again ...

To reduce the randomness in NN and pytorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

In [61]:
import torch

# create a two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5209, 0.3779, 0.1501, 0.0790],
        [0.5222, 0.0529, 0.8162, 0.1640],
        [0.7001, 0.0785, 0.4074, 0.5536]])
tensor([[0.3825, 0.4635, 0.4115, 0.6353],
        [0.9600, 0.4137, 0.8730, 0.1950],
        [0.1682, 0.6703, 0.1276, 0.7739]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [64]:
# lets makse some random but reproducible tensors

import torch

# set random seed
randomSeed = 42
torch.manual_seed(randomSeed)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(randomSeed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch object on the GPU (make faster)

In [ ]:
# 1. getting a GPU


In [65]:
!Nvidia-smi

/bin/bash: line 1: Nvidia-smi: command not found


In [66]:
# check for GPU accees with pytorch
import torch
torch.cuda.is_available()

False

In [67]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [68]:
# count number of device
torch.cuda.device_count()

0

## putting tensord and models on the gpu

In [71]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# tenosr not on gpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [72]:
tensor_on_gpu = tensor = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

## 4. Moving tensor back to CPU

In [73]:
# if tensor in GPU, cant transform to numpy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [74]:
# tofix the gpu tensor with numpy issue, we can first set in on the cpu

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
## Exercise